### ISSUE TITLE
Realizar Teste de Sistema

### ISSUE THREAD

**Issue by gabrielaimeeg** [gabrielaimeeg/DroidMetronome#17]
Executar teste no sistema do ponto de vista do usuário final, simulando situações de rotina.

**Comment by gustavosotnas** [comment]
Não foi realizado na sprint 1, será realizado na ***Sprint* 2**.

**Comment by gustavosotnas** [comment]
Os Testes de Sistema serão feitos manualmente com a execução do aplicativo em um smartphone real com o uso sendo feito por um usuário que tem experiência com Música.

**Comment by koziel101** [comment]
Não foi realizado na sprint 2, será realizado na ***Sprint* 3**.
