### ISSUE TITLE
Alteração do Processo de Manutenção

### ISSUE THREAD

**Issue by gustavosotnas** [gabrielaimeeg/DroidMetronome#36]
Foi observado que o Processo de Manutenção (feito anteriormente em HTML e enviado para o [Prof. Juliano]() via email) possui vários problemas:

- Notação BPMN no Macro Fluxo do processo incorreta;
- As atividades descritas no Processo não são as mesmas das definidas no Macro Fluxo;
- Não há ligação de atividades com as de Gerência de Configuração (GCS);
- Métricas do processo de manutenção complexas de serem aplicadas;
- Não há clareza na descrição do ciclo de vida de manutenção;
- Não há definição clara de papéis e responsabilidades dos *Stakeholders* (interessados);

**Comment by PedroDrim** [comment]
# Análise da mudança

A análise da mudança será feita com base na seguinte estrutura:
       1. Análise de viabilidade e riscos
       2. Análise de custo
       3. Análise de impacto

## 1. Análise de viabilidade e riscos

Por meio da análise de riscos ,foi verificado a importância e o impacto da manutenção dentro do projeto.
O resultado obtido foi : A modificação foi considerada **viável** para a realização.
* É válido lembrar que o atraso na implementação da modificação solicitada á tornará praticamente inviável.
Segue abaixo os atributos de viabilidade analisados com suas respectivas notas : 

| Atributo quanto ao tempo | Valor   |
|--------------------------|---------|
|    Longo                 |    4    |
|    Médio                 |    3    |
|    Curto                 |    1    |
|    Atrasado              |   0.5   |

Resultado do Atributo "Tempo" : 1 (Curto)

| Atributo quanto ao tipo de modificação | Valor   |
|----------------------------------------|---------|
|    Corrigir funcionalidades            |    3    |
|    Melhorar funcionalidades            |    2    |
|    Acrescentar funcionalidade          |    1    |

Resultado do atributo "Tipo de modificação : 3 (Corrigir funcionalidades)

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" : 3 (Modificação de funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

| Tipo de viabilidade                    | Valor total |
|----------------------------------------|-------------|
|    Viável                              |   9 - 36    |
|    Parcialmente Viável                 |   2 - 8     |
|    Inviável                            | abaixo de 2 |  

Resultado de viabilidade: 1 * 3 * 3 = 9 (Viável)

## 2. Análise de custos

Por meio da análise de custos,foi verificado os recursos disponibilizados para a modificação.
O resultado obtido foi : A modificação foi considerada de **alto custo**.
Segue abaixo os atributos de custos analisados com suas respectivas notas : 

| Atributo quanto ao tipo de modificação | Valor |
|----------------------------------------|-------|
|    Corrigir funcionalidades            |  3    |
|    Melhorar funcionalidades            |  2    |
|    Acrescentar funcionalidade          |  1    |

Resultado do atributo "Tipo de modificação : 3 (Corrigir funcionalidades) 

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" :  3 (Modificação em funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

|    Tipo de custo                       | Valor total |
|----------------------------------------|-------------|
|    Alto custo                          |   9 - 4     |
|    Médio custo                         |   2 - 3     |
|    Baixo custo                         |     1       |

Resultado de custo : 3 * 3 = 9 (Alto custo)

## 3. Análise de impacto

* Descrição da manutenção: Refazer o macrofluxo de manutenção utilizando a notação correta BPMN, possibilitando o detalhamento das atividades nele descritas e correlação com a área de gerência de configuração.
Alterar as métricas do processo de manutenção por métricas mais viáveis.
Descrever com clareza o ciclo de vida, os papéis e responsabilidades dos interessados.

* Áreas modificadas: Manutenção

* Outras áreas afetadas: Desenvolvimento, Verificação ,Validação ,Gerência da configuração ,Qualidade , Gerencia de projeto e Arquitetura.

**Comment by gabrielaimeeg** [comment]
# Planejamento de mudanças

## 1. Identificação e descrição dos elementos

**1.1** Refazer o macrofluxo com notação BPMN;
**1.2** Detalhar atividades mostradas no macrofluxo seguindo template<LINKAR TEMPLATE QUANDO PASSAR PRO REPOSITÓRIO NOVO> do Processo;
**1.3** Referenciar as atividades de Gerência de Configuração (GCS);
**1.4** Alterar as métricas para "Quantidade de manutenções corretivas aplicadas", "Análise de efeitos colaterais após a manutenção" e "Análise de manutenibilidade pós manutenção"; detalha-las seguindo template"<LINKAR TEMPLATE QUANDO PASSAR PRO REPOSITÓRIO NOVO>; 
**1.5** Refazer, de forma clara, o ciclo de vida de manutenção;
**1.6** Atribuir papéis e responsabilidades aos Stakeholders (interessados);

## 2. Atribuição de responsabilidades

| Nome do responsável       | elemento especificado       |
|---------------------------|-----------------------------|
| Gustavo Moraes           | **1.1** |
| Julianny Alves           | **1.2** |
| Paulo de Oliveira           | **1.3** |
| Renan Ofugi          | **1.4** |
| Hiago Koziel           | **1.5** |
| Pedro Henrique           | **1.6** |
