### ISSUE TITLE
Alteração do Plano de Projeto

### ISSUE THREAD

**Issue by gabrielaimeeg** [gabrielaimeeg/DroidMetronome#37]
O Plano de Projeto apresenta vários problemas:
* O plano carece de mais consistência entre as referências aos casos de uso
* Definição clara do escopo das sprints
* Formalização do critério utilizado na definição da complexidade das tarefas definidas da sprint planning 2
* Citação das referências dos outros planos
* Esclarecimento da quantidade total de sprints do projeto
* Melhoramento e detalhamento das etapas do ciclo de vida
* Definição do custo não somente financeiro do projeto (mas também em questão de esforço)
* Especificação de forma mais clara das etapas em que ocorrerão as retrospectivas, reviews e cerimônias
* Definição da prioridade de tratamento dos riscos
* Justificar a escolha dos representantes de cada papel e a explicitação do comprometimento da equipe com o plano.

**Comment by PedroDrim** [comment]
# Análise da mudança

A análise da mudança será feita com base na seguinte estrutura:
       1. Análise de viabilidade e riscos
       2. Análise de custo
       3. Análise de impacto

## 1. Análise de viabilidade e riscos

Por meio da análise de riscos ,foi verificado a importância e o impacto da manutenção dentro do projeto.
O resultado obtido foi : A modificação foi considerada **viável** para a realização.
* É válido lembrar que o atraso na implementação da modificação solicitada á tornará praticamente inviável.
Segue abaixo os atributos de viabilidade analisados com suas respectivas notas : 

| Atributo quanto ao tempo | Valor   |
|--------------------------|---------|
|    Longo                 |    4    |
|    Médio                 |    3    |
|    Curto                 |    1    |
|    Atrasado              |   0.5   |

Resultado do Atributo "Tempo" : 1 (Curto)

| Atributo quanto ao tipo de modificação | Valor   |
|----------------------------------------|---------|
|    Corrigir funcionalidades            |    3    |
|    Melhorar funcionalidades            |    2    |
|    Acrescentar funcionalidade          |    1    |

Resultado do atributo "Tipo de modificação : 3 (Corrigir funcionalidades)

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" : 3 (Modificação de funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

| Tipo de viabilidade                    | Valor total |
|----------------------------------------|-------------|
|    Viável                              |   9 - 36    |
|    Parcialmente Viável                 |   2 - 8     |
|    Inviável                            | abaixo de 2 |  

Resultado de viabilidade: 1 * 3 * 3 = 9 (Viável)

## 2. Análise de custos

Por meio da análise de custos,foi verificado os recursos disponibilizados para a modificação.
O resultado obtido foi : A modificação foi considerada de **alto custo**.
Segue abaixo os atributos de custos analisados com suas respectivas notas : 

| Atributo quanto ao tipo de modificação | Valor |
|----------------------------------------|-------|
|    Corrigir funcionalidades            |  3    |
|    Melhorar funcionalidades            |  2    |
|    Acrescentar funcionalidade          |  1    |

Resultado do atributo "Tipo de modificação : 3 (Corrigir funcionalidades) 

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" :  3 (Modificação em funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

|    Tipo de custo                       | Valor total |
|----------------------------------------|-------------|
|    Alto custo                          |   9 - 4     |
|    Médio custo                         |   2 - 3     |
|    Baixo custo                         |     1       |

Resultado de custo : 3 * 3 = 9 (Alto custo)

## 3. Análise de impacto

* Descrição da manutenção:
Deverá ser melhorado a consistência entre as referências aos casos de uso de forma a evitar ambiguidades.
Definir melhor o escopo das sprints.
Formalização do critério utilizado na definição da complexidade das tarefas definidas da sprint planning 2.
Referênciar o plano de projeto á outros planos.
Esclarecimento da quantidade total de sprints do projeto.
Melhoramento e detalhamento das etapas do ciclo de vida.
Definição do custo ,seja ele físico, intelectual, financeiro ou temporal.
Especificação de forma mais clara das etapas em que ocorrerão as retrospectivas, reviews e cerimônias.
Definição da prioridade de tratamento dos riscos.
Justificar a escolha dos representantes de cada papel e a explicitação do comprometimento da equipe com o plano.

* Áreas modificadas: Gerência de projeto.

* Outras áreas afetadas: Desenvolvimento, Verificação ,Validação ,Gerência da configuração ,Qualidade , engenharia de requisitos, manutenção e Arquitetura.

**Comment by gabrielaimeeg** [comment]
# Planejamento de mudanças

## 1. Identificação e descrição dos elementos

**1.1** Feratorar referências aos casos de uso
**1.2** Definir claramente do escopo das sprints
**1.3** Formalizar do critério utilizado na definição da complexidade das tarefas definidas da sprint planning 2
**1.4** Referências documentos citados
**1.5** Esclarecer quantidade total de sprints do projeto
**1.4** Melhoramento e detalhamento das etapas do ciclo de vida
**1.6** Definir do custo não somente financeiro do projeto (mas também em questão de esforço)
**1.7** Especificar claramente as etapas em que ocorrerão as retrospectivas, reviews e cerimônias
**1.8** Definição da prioridade de tratamento dos riscos
**1.9** Justificar a escolha dos representantes de cada papel e a explicitação do comprometimento da equipe com o plano.

## 2. Atribuição de responsabilidades

| Nome do responsável       | elemento especificado       |
|---------------------------|-----------------------------|
|   Gabriela Aimée         | **1.1** |
| Julianny Alves           | **1.2** |
| Paulo de Oliveira           | **1.3** |
| Renan Ofugi          | **1.4** |
| Hiago Koziel           | **1.5** |
| Pedro Henrique          | **1.6** |
| Gustavo Moraes      | **1.7** |
| Hiago Koziel           | **1.8** |
| Gabriela Aimée           | **1.9** |
