### ISSUE TITLE
Alteração no Plano de GCS

### ISSUE THREAD

**Issue by gustavosotnas** [gabrielaimeeg/DroidMetronome#42]
O plano de GCS deve:
* Refazer a estrutura do repositório de versões principal:
    * com a pasta "Processo" e o PDS em formato PDF dentro;
    * com a pasta "registros de aprovação" com scan's de assinaturas nossas em um papel;
* Especificar onde deve estar cada um dos artefatos de projeto no repositório em lista;
* Retirar redundâncias e texto desnecessário do Plano, para deixá-lo mais leve de se ler.

**Comment by PedroDrim** [comment]
# Análise da mudança

A análise da mudança será feita com base na seguinte estrutura:
       1. Análise de viabilidade e riscos
       2. Análise de custo
       3. Análise de impacto

## 1. Análise de viabilidade e riscos

Por meio da análise de riscos ,foi verificado a importância e o impacto da manutenção dentro do projeto.
O resultado obtido foi : A modificação foi considerada **viável** para a realização.
* É válido lembrar que o atraso na implementação da modificação solicitada á tornará praticamente inviável.
Segue abaixo os atributos de viabilidade analisados com suas respectivas notas : 

| Atributo quanto ao tempo | Valor   |
|--------------------------|---------|
|    Longo                 |    4    |
|    Médio                 |    3    |
|    Curto                 |    1    |
|    Atrasado              |   0.5   |

Resultado do Atributo "Tempo" : 1 (Curto)

| Atributo quanto ao tipo de modificação | Valor   |
|----------------------------------------|---------|
|    Corrigir funcionalidades            |    3    |
|    Melhorar funcionalidades            |    2    |
|    Acrescentar funcionalidade          |    1    |

Resultado do atributo "Tipo de modificação : 3 (Corrigir funcionalidades)

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" : 3 (Modificação de funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

| Tipo de viabilidade                    | Valor total |
|----------------------------------------|-------------|
|    Viável                              |   9 - 36    |
|    Parcialmente Viável                 |   2 - 8     |
|    Inviável                            | abaixo de 2 |  

Resultado de viabilidade: 1 * 3 * 3 = 9 (Viável)

## 2. Análise de custos

Por meio da análise de custos,foi verificado os recursos disponibilizados para a modificação.
O resultado obtido foi : A modificação foi considerada de **alto custo**.
Segue abaixo os atributos de custos analisados com suas respectivas notas : 

| Atributo quanto ao tipo de modificação | Valor |
|----------------------------------------|-------|
|    Corrigir funcionalidades            |  3    |
|    Melhorar funcionalidades            |  2    |
|    Acrescentar funcionalidade          |  1    |

Resultado do atributo "Tipo de modificação : 3 (Corrigir funcionalidades) 

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" :  3 (Modificação em funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

|    Tipo de custo                       | Valor total |
|----------------------------------------|-------------|
|    Alto custo                          |   9 - 4     |
|    Médio custo                         |   2 - 3     |
|    Baixo custo                         |     1       |

Resultado de custo : 3 * 3 = 9 (Alto custo)

## 3. Análise de impacto

* Descrição da manutenção: Deverá ser feito no plano de configuração, refazer a estrutura do repositório de versões principal ,de forma a classificar melhor os itens de configuração.
Listagem de **todos** os artefatos de projeto existentes no repositório.
Remover redundâncias existentes no plano de GCS.

* Áreas modificadas: Gerência de configuração

* Outras áreas afetadas: Desenvolvimento, Verificação ,Validação ,engenharia de requisitos ,Qualidade , Gerencia de projeto, manutenção e Arquitetura.

**Comment by gabrielaimeeg** [comment]
# Planejamento de mudanças

## 1. Identificação e descrição dos elementos

**1.1** Refazer a estrutura do repositório de versões principal: com a pasta "Processo" e o PDS em formato PDF dentro; com a pasta "registros de aprovação" com scan's de assinaturas nossas em um papel;
**1.2** Especificar onde deve estar cada um dos artefatos de projeto no repositório em lista;
**1.3** Retirar redundâncias e texto desnecessário do Plano, para deixá-lo mais leve de se ler.

## 2. Atribuição de responsabilidades

| Nome do responsável       | elemento especificado       |
|---------------------------|-----------------------------|
| Gustavo Moraes           | **1.1** |
| Gabriela Aimée          | **1.2** |
| Pedro Henrqiue           | **1.3** |
