### ISSUE TITLE
Refatoração do EOR

### ISSUE THREAD

**Issue by gustavosotnas** [gabrielaimeeg/DroidMetronome#43]
O EOR apresenta vários problemas como:
* Não contempla GRE algum no MPS.BR;
* Há problemas na formatação do documento;
* Há inconsistência de nomenclatura de Casos de Uso e requisitos;
* Não há clareza e legibilidade textual no documento.

**Comment by PedroDrim** [comment]
# Análise da mudança

A análise da mudança será feita com base na seguinte estrutura:
       1. Análise de viabilidade e riscos
       2. Análise de custo
       3. Análise de impacto

## 1. Análise de viabilidade e riscos

Por meio da análise de riscos ,foi verificado a importância e o impacto da manutenção dentro do projeto.
O resultado obtido foi : A modificação foi considerada **viável** para a realização.
* É válido lembrar que o atraso na implementação da modificação solicitada á tornará praticamente inviável.
Segue abaixo os atributos de viabilidade analisados com suas respectivas notas : 

| Atributo quanto ao tempo | Valor   |
|--------------------------|---------|
|    Longo                 |    4    |
|    Médio                 |    3    |
|    Curto                 |    1    |
|    Atrasado              |   0.5   |

Resultado do Atributo "Tempo" : 1 (Curto)

| Atributo quanto ao tipo de modificação | Valor   |
|----------------------------------------|---------|
|    Corrigir funcionalidades            |    3    |
|    Melhorar funcionalidades            |    2    |
|    Acrescentar funcionalidade          |    1    |

Resultado do atributo "Tipo de modificação : 3 (Corrigir funcionalidades)

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" : 3 (Modificação de funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

| Tipo de viabilidade                    | Valor total |
|----------------------------------------|-------------|
|    Viável                              |   9 - 36    |
|    Parcialmente Viável                 |   2 - 8     |
|    Inviável                            | abaixo de 2 |  

Resultado de viabilidade: 1 * 3 * 3 = 9 (Viável)

## 2. Análise de custos

Por meio da análise de custos,foi verificado os recursos disponibilizados para a modificação.
O resultado obtido foi : A modificação foi considerada de **alto custo**.
Segue abaixo os atributos de custos analisados com suas respectivas notas : 

| Atributo quanto ao tipo de modificação | Valor |
|----------------------------------------|-------|
|    Corrigir funcionalidades            |  3    |
|    Melhorar funcionalidades            |  2    |
|    Acrescentar funcionalidade          |  1    |

Resultado do atributo "Tipo de modificação : 3 (Corrigir funcionalidades) 

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" :  3 (Modificação em funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

|    Tipo de custo                       | Valor total |
|----------------------------------------|-------------|
|    Alto custo                          |   9 - 4     |
|    Médio custo                         |   2 - 3     |
|    Baixo custo                         |     1       |

Resultado de custo : 3 * 3 = 9 (Alto custo)

## 3. Análise de impacto

* Descrição da manutenção: O EOR deverá contemplar e implementar o GRE com base no Mps-Br nível G.
Corrigir inconsistências de nomenclatura de Casos de Uso e requisitos além da melhoria na legibilidade do documento.
Deverá ser feita também no EOR a correção da formatação do documento.

* Áreas modificadas: Engenharia de requisitos

* Outras áreas afetadas: Desenvolvimento, Verificação ,Validação ,Gerência da configuração ,Qualidade , Gerencia de projeto, manutenção e Arquitetura.
