### ISSUE TITLE
Adição de novo membro

### ISSUE THREAD

**Issue by gabrielaimeeg** [gabrielaimeeg/DroidMetronome#59]
Devido a pedidos da professora Adriana, há a necessidade de adição de um novo membro no Projeto: [Gleibson Silva](https://github.com/GleibsonSilva), que auxiliará na Gerência de Projetos.

**Comment by PedroDrim** [comment]
# Análise da mudança

A análise da mudança será feita com base na seguinte estrutura:
       1. Análise de viabilidade e riscos
       2. Análise de custo
       3. Análise de impacto

## 1. Análise de viabilidade e riscos

Por meio da análise de riscos ,foi verificado a importância e o impacto dessa modificação dentro do projeto.
O resultado obtido foi : A modificação foi considerada **viável** para a realização.
Segue abaixo os atributos de viabilidade analisados com suas respectivas notas : 

| Atributo quanto a experiência | Valor   |
|--------------------------|---------|
|    Muito experiente                 |    4    |
|    Experiente      |    3    |
|    Pouco experiente                 |    1    |
|    Inexperiente              |   0.5   |

Resultado do Atributo "Experiência" : 3 (Experiente)

| Atributo quanto ao tempo de projeto | Valor   |
|----------------------------------------|---------|
|    Alto           |    3    |
|    Médio            |    2    |
|    Baixo          |    1    |

Resultado do atributo "Tempo de projeto" : 2 (Médio)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

| Tipo de viabilidade                    | Valor total |
|----------------------------------------|-------------|
|    Viável                              |   9 -  12  |
|    Parcialmente Viável                 |   2 - 8     |
|    Inviável                            | abaixo de 2 |  

Resultado de viabilidade: 1 * 3 * 3 = 9 (Viável)

## 2. Análise de custos

Por meio da análise de custos,foi verificado os recursos disponibilizados para a modificação.
O resultado obtido foi : A modificação foi considerada de **alto custo**.
Segue abaixo os atributos de custos analisados com suas respectivas notas : 

| Atributo quanto ao tipo de modificação | Valor |
|----------------------------------------|-------|
|    Corrigir funcionalidades            |  3    |
|    Melhorar funcionalidades            |  2    |
|    Acrescentar funcionalidade          |  1    |

Resultado do atributo "Tipo de modificação : 3 (Corrigir funcionalidades) 

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" :  3 (Modificação em funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

|    Tipo de custo                       | Valor total |
|----------------------------------------|-------------|
|    Alto custo                          |   9 - 4     |
|    Médio custo                         |   2 - 3     |
|    Baixo custo                         |     1       |

Resultado de custo : 3 * 3 = 9 (Alto custo)

## 3. Análise de impacto

* Descrição da manutenção: O EOR deverá contemplar e implementar o GRE com base no Mps-Br nível G.
Corrigir inconsistências de nomenclatura de Casos de Uso e requisitos além da melhoria na legibilidade do documento.
Deverá ser feita também no EOR a correção da formatação do documento.

* Áreas modificadas: Engenharia de requisitos

* Outras áreas afetadas: Desenvolvimento, Verificação ,Validação ,Gerência da configuração ,Qualidade , Gerencia de projeto, manutenção e Arquitetura.

**Comment by gabrielaimeeg** [comment]
# Planejamento de mudanças

## 1. Identificação e descrição dos elementos

**1.1** Alocação do novo membro a um papel
**1.2** Redistribuição das atividades
**1.3** Relatar situação atual do projeto ao novo membro

## 2. Atribuição de responsabilidades

| Nome do responsável       | elemento especificado       |
|---------------------------|-----------------------------|
|   Gabriela Aimée         | **1.1** |
| Julianny Alves           | **1.2** |
| Paulo de Oliveira           | **1.3** |
