### ISSUE TITLE
Refatoração do Plano de Projeto

### ISSUE THREAD

**Issue by gabrielaimeeg** [gabrielaimeeg/DroidMetronome#60]
Baseado nos resultados obtidos na segunda apresentação do projeto à professora Adriana, viu-se a necessidade da refatoração do Plano para corrigir os seguintes tópicos:
* Simplificar plano e retirar informações desnecessárias
* Melhorar os critérios de estimativas
* Igualar as horas definidas como esforço no plano, com as horas distribuídas no waffle.io
*  Definir horas para as atividades de planejamento, não apenas as de execução
* Arrumar a prioridade dos riscos(ordem invertida)
* Descrever e detalhas as atividades dos papéis no Scrum(PO, SM e ST)
* No Relatório de Monitoramento deve constar aqueles que irão tratar o risco que foi concretizado e qual foi a estratégia de reparação adotada para resolvê-lo
* Adicionar Relatório de Marco, para informar pessoas fora do projeto do que foi realizado e produzido

**Comment by PedroDrim** [comment]
# Análise da mudança

A análise da mudança será feita com base na seguinte estrutura:
       1. Análise de viabilidade e riscos
       2. Análise de custo
       3. Análise de impacto

## 1. Análise de viabilidade e riscos

Por meio da análise de riscos ,foi verificado a importância e o impacto da manutenção dentro do projeto.
O resultado obtido foi : A modificação foi considerada **viável** para a realização.
* É válido lembrar que o atraso na implementação da modificação solicitada á tornará praticamente inviável.
Segue abaixo os atributos de viabilidade analisados com suas respectivas notas : 

| Atributo quanto ao tempo | Valor   |
|--------------------------|---------|
|    Longo                 |    4    |
|    Médio                 |    3    |
|    Curto                 |    1    |
|    Atrasado              |   0.5   |

Resultado do Atributo "Tempo" : 3 (Médio)

| Atributo quanto ao tipo de modificação | Valor   |
|----------------------------------------|---------|
|    Corrigir funcionalidades            |    3    |
|    Melhorar funcionalidades            |    2    |
|    Acrescentar funcionalidade          |    1    |

Resultado do atributo "Tipo de modificação : 2 (Melhorar funcionalidades)

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" : 3 (Modificação de funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

| Tipo de viabilidade                    | Valor total |
|----------------------------------------|-------------|
|    Viável                              |   9 - 36    |
|    Parcialmente Viável                 |   2 - 8     |
|    Inviável                            | abaixo de 2 |  

Resultado de viabilidade: 3 * 2 * 3 = 18 (Viável)

## 2. Análise de custos

Por meio da análise de custos,foi verificado os recursos disponibilizados para a modificação.
O resultado obtido foi : A modificação foi considerada de **alto custo**.
Segue abaixo os atributos de custos analisados com suas respectivas notas : 

| Atributo quanto ao tipo de modificação | Valor |
|----------------------------------------|-------|
|    Corrigir funcionalidades            |  3    |
|    Melhorar funcionalidades            |  2    |
|    Acrescentar funcionalidade          |  1    |

Resultado do atributo "Tipo de modificação : 2 (Melhorar funcionalidades) 

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" :  3 (Modificação em funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

|    Tipo de custo                       | Valor total |
|----------------------------------------|-------------|
|    Alto custo                          |   9 - 4     |
|    Médio custo                         |   2 - 3     |
|    Baixo custo                         |     1       |

Resultado de custo : 2 * 3 = 9 (Alto custo)

## 3. Análise de impacto

* Descrição da manutenção:
O plano deverá ser simplificado aonde, informações redundantes e desnecessárias serão removidas.
Melhorar os critérios de estimativas com o objetivo de definir melhor o tempo gasto em cada área (seja planejamento ou execução), de forma a igualar as horas definidas como esforço no plano com as horas no waffle.io.
Arrumar a prioridade dos riscos que se encontra com a ordem invertida.
Descrever e detalhas as atividades dos papéis no Scrum (Product Owner, Scrum Master e Scrum Team).
No Relatório de Monitoramento deve constar aqueles que irão tratar o risco que foi concretizado e qual foi a estratégia de reparação adotada para resolvê-lo
Adicionar Relatório de Marco, para informar pessoas fora do projeto do que foi realizado e produzido

* Áreas modificadas: Engenharia de requisitos

* Outras áreas afetadas: Desenvolvimento, Verificação ,Validação ,Gerência da configuração ,Qualidade , Gerencia de projeto, manutenção e Arquitetura.

**Comment by gabrielaimeeg** [comment]
# Planejamento de mudanças

## 1. Identificação e descrição dos elementos

**1.1** Simplificar plano e retirar informações desnecessárias
**1.2** Melhorar os critérios de estimativas
**1.3** Igualar as horas definidas como esforço no plano, com as horas distribuídas no waffle.io
**1.4** Definir horas para as atividades de planejamento, não apenas as de execução
**1.5** Arrumar a prioridade dos riscos(ordem invertida)
**1.6** Descrever e detalhas as atividades dos papéis no Scrum(PO, SM e ST)
**1.7** No Relatório de Monitoramento deve constar aqueles que irão tratar o risco que foi concretizado e qual foi a estratégia de reparação adotada para resolvê-lo
**1.8** Adicionar Relatório de Marco, para informar pessoas fora do projeto do que foi realizado e produzido

## 2. Atribuição de responsabilidades

| Nome do responsável       | elemento especificado       |
|---------------------------|-----------------------------|
|   Gabriela Aimée         | **1.1** |
|  Julianny Alves           | **1.2** |
|  Paulo de Oliveira           | **1.3** |
|  Pedro Henrique  | **1.4** |
| Gleibson Silva  | **1.5** |
| Gustavo Moraes | **1.6** |
| Renan Ofugi | **1.7** |
| Hiago Koziel | **1.8** |
