### ISSUE TITLE
Refatoração do Plano de Gerência da Configuração

### ISSUE THREAD

**Issue by gabrielaimeeg** [gabrielaimeeg/DroidMetronome#61]
Baseado nas apresentações do Plano de Gerência de Configuração à professora Adriana e ao professor Rubens, viu-se necessário acrescentar as seguintes alterações:
* Usar ABNT para fazer referências a outros artefatos
* Mudar as nomenclaturas de "seção" para "capítulo"
* Acrescentar requisitos mínimos de hardware
* Melhorar legibilidade do Plano, para torná-lo mais direto (Scrum puro)

**Comment by PedroDrim** [comment]
# Análise da mudança

A análise da mudança será feita com base na seguinte estrutura:
       1. Análise de viabilidade e riscos
       2. Análise de custo
       3. Análise de impacto

## 1. Análise de viabilidade e riscos

Por meio da análise de riscos ,foi verificado a importância e o impacto da manutenção dentro do projeto.
O resultado obtido foi : A modificação foi considerada **viável** para a realização.
* É válido lembrar que o atraso na implementação da modificação solicitada á tornará praticamente inviável.
Segue abaixo os atributos de viabilidade analisados com suas respectivas notas : 

| Atributo quanto ao tempo | Valor   |
|--------------------------|---------|
|    Longo                 |    4    |
|    Médio                 |    3    |
|    Curto                 |    1    |
|    Atrasado              |   0.5   |

Resultado do Atributo "Tempo" : 3 (Médio)

| Atributo quanto ao tipo de modificação | Valor   |
|----------------------------------------|---------|
|    Corrigir funcionalidades            |    3    |
|    Melhorar funcionalidades            |    2    |
|    Acrescentar funcionalidade          |    1    |

Resultado do atributo "Tipo de modificação : 2 (Melhorar funcionalidades)

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" : 3 (Modificação de funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

| Tipo de viabilidade                    | Valor total |
|----------------------------------------|-------------|
|    Viável                              |   9 - 36    |
|    Parcialmente Viável                 |   2 - 8     |
|    Inviável                            | abaixo de 2 |  

Resultado de viabilidade: 3 * 2 * 3 = 18 (Viável)

## 2. Análise de custos

Por meio da análise de custos,foi verificado os recursos disponibilizados para a modificação.
O resultado obtido foi : A modificação foi considerada de **alto custo**.
Segue abaixo os atributos de custos analisados com suas respectivas notas : 

| Atributo quanto ao tipo de modificação | Valor |
|----------------------------------------|-------|
|    Corrigir funcionalidades            |  3    |
|    Melhorar funcionalidades            |  2    |
|    Acrescentar funcionalidade          |  1    |

Resultado do atributo "Tipo de modificação : 2 (Melhorar funcionalidades) 

| Atributo quanto ao risco               | Valor   |
|----------------------------------------|---------|
|    Modificação em funções essenciais   |    3    |
|    Modificação em funções secundárias  |    2    |
|    Modificação em funções opcionais    |    1    |

Resultado do atributo "Risco" :  3 (Modificação em funções essenciais)

A classificação final é dada pelo produto dos resultados obtidos nos atributos acima.

|    Tipo de custo                       | Valor total |
|----------------------------------------|-------------|
|    Alto custo                          |   9 - 4     |
|    Médio custo                         |   2 - 3     |
|    Baixo custo                         |     1       |

Resultado de custo : 2 * 3 = 9 (Alto custo)

## 3. Análise de impacto

* Descrição da manutenção:
O plano de Gerencia de configuração deverá ser refatorado de forma a usar ABNT para fazer referências a outros artefatos com o objetivo de melhorar legibilidade do Plano.
Mudar as nomenclaturas de "seção" para "capítulo"
Acrescentar requisitos mínimos de hardware

* Áreas modificadas: Gerência da configuração 

* Outras áreas afetadas: Desenvolvimento, Verificação ,Validação ,Engenharia de requisitos ,Qualidade , Gerencia de projeto, manutenção e Arquitetura.

**Comment by gabrielaimeeg** [comment]
# Planejamento de mudanças

## 1. Identificação e descrição dos elementos

**1.2** Usar ABNT para fazer referências a outros artefatos
**1.3** Mudar as nomenclaturas de "seção" para "capítulo"
**1.4** Acrescentar requisitos mínimos de hardware
**1.5** Melhorar legibilidade do Plano

## 2. Atribuição de responsabilidades

| Nome do responsável       | elemento especificado       |
|---------------------------|-----------------------------|
|   Gabriela Aimée         | **1.1** |
|  Julianny Alves           | **1.2** |
|  Paulo de Oliveira           | **1.3** |
|  Pedro Henrique  | **1.4** |
| Gleibson Silva  | **1.5** |

**Comment by gustavosotnas** [comment]
Refatorado na issue [a39a8c0](https://github.com/gabrielaimeeg/DroidMetronome/wiki/Plano-de-Gerência-de-Configuração/a39a8c0b6dcb27f7ac91f6c35ce1f1b731e304f5) do Wiki
