### ISSUE TITLE
Incremento no diagrama de componentes e no de classe

### ISSUE THREAD

**Issue by koziel101** [gabrielaimeeg/DroidMetronome#66]
Adicionar dois casos de uso para esta sprint

**Comment by PedroDrim** [comment]
# Análise da mudança

A análise da mudança será feita com base na seguinte estrutura:
       1. Análise de viabilidade e riscos

## 1. Análise de viabilidade e riscos

A requisição possui ambiguidade em relação aos casos de uso ( pois eles devem ser especificados ).
Devido a tal ambiguidade a análise de mudança não poderá ser realizada até a realização da correção.
Por esse motivo a solicitação de mudança foi considerada **inviável**.
