### ISSUE TITLE
Refatorar Plano de V&V

### ISSUE THREAD

**Issue by gabrielaimeeg** [gabrielaimeeg/DroidMetronome#78]

**Comment by gustavosotnas** [comment]
Refatorado Plano de V&V no commit [d7db22](https://github.com/gabrielaimeeg/DroidMetronome/wiki/Plano-de-Verifica%C3%A7%C3%A3o-e-Valida%C3%A7%C3%A3o/d7db22242da7d9dd2c7da936fcfc964590b25161) da Wiki.
